const ACTION_TYPES = {
  // TODO_CREATE: 'TODO_CREATE',
  CREATE_TODO_ACTION: 'CREATE_TODO_ACTION',
  CREATE_TODO_REQUEST: 'CREATE_TODO_REQUEST',
  CREATE_TODO_SUCCESS: 'CREATE_TODO_SUCCESS',
  CREATE_TODO_ERROR: 'CREATE_TODO_ERROR',
  //
  GET_TODO_ACTION: 'GET_TODO_ACTION',
  GET_TODO_REQUEST: 'GET_TODO_REQUEST',
  GET_TODO_SUCCESS: 'GET_TODO_SUCCESS',
  GET_TODO_ERROR: 'GET_TODO_ERROR',
  //
  // TODO_DELETE: 'TODO_DELETE',
  DELETE_TODO_ACTION: 'DELETE_TODO_ACTION',
  DELETE_TODO_REQUEST: 'DELETE_TODO_REQUEST',
  DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
  DELETE_TODO_ERROR: 'DELETE_TODO_ERROR',
  //
  // TODO_CHEK: 'TODO_CHEK',
  ISDONE_TODO_ACTION: 'ISDONE_TODO_ACTION',
  ISDONE_TODO_REQUEST: 'ISDONE_TODO_REQUEST',
  ISDONE_TODO_SUCCESS: 'ISDONE_TODO_SUCCESS',
  ISDONE_TODO_ERROR: 'ISDONE_TODO_ERROR',
};

export default ACTION_TYPES;
